name: running test,build image, push registry, deploy
on:
  push:
    branches: [main]

jobs:
  buildimage:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create env
        run: |
          echo " ${{ secrets.ENV_PROJECT }} " > .env
      - name: build image
        run: docker build -t hantzord/foodresq:latest .
      - name: login registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push image
        run: docker push hantzord/foodresq:latest

  deployec2:
    name: deploy ec2
    runs-on: ubuntu-latest
    needs: buildimage
    steps:
      - uses: actions/checkout@v2
      - name: deploy ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/foodresq
            docker pull hantzord/foodresq:latest
            docker run -d -p 3000:3000 hantzord/foodresq:latest